//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.Critique = new HashSet<Critique>();
            this.Inventaire = new HashSet<Inventaire>();
            this.Panier = new HashSet<Panier>();
        }

        public int idItem { get; set; }

        public string nom { get; set; }

        public int qtStock { get; set; }

        public int prix { get; set; }
        public byte[] photo { get; set; }

        public string ItemLogo { get; set; }

        public string typeItem { get; set; }

        public string flagDispo { get; set; }


        public virtual Arme Arme { get; set; }
        public virtual Armure Armure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Critique> Critique { get; set; }
        public virtual elements elements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventaire> Inventaire { get; set; }
        public virtual Magasin Magasin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Panier> Panier { get; set; }
        public virtual Potion Potion { get; set; }
    }
}
