//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Collections.Generic;
    using System.Security.Cryptography;
    using System.Text;

    public partial class Joueurs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Joueurs()
        {
            this.Critique = new HashSet<Critique>();
            this.Inventaire = new HashSet<Inventaire>();
            this.Panier = new HashSet<Panier>();
            this.Statistiques = new HashSet<Statistiques>();
            this.StatsQstScience = new HashSet<StatsQstScience>();
        }

        public int idJoueur { get; set; }

        public string alias { get; set; }

        public string nom { get; set; }

        public string prenom { get; set; }

        public string email { get; set; }
        public string niveau { get; set; }
        private string _password { get; set; }

        public string password
        {
            get { return _password; }
            set
            {
                _password = value;
                if (value != null)
                    mdp = HashPassword(value);
            }
        }

        public byte[] mdp { get; private set; }

        private byte[] HashPassword(string password)
        {
            using (SHA512 sha512 = SHA512.Create())
            {
                return sha512.ComputeHash(Encoding.UTF8.GetBytes(password));
            }
        }
        public byte estAdmin { get; set; }
        public byte estAlchimiste { get; set; }
        public int solde { get; set; }
        public byte[] Avatar { get; set; }
        public string Logo { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Critique> Critique { get; set; }
        public virtual potionConcocter potionConcocter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventaire> Inventaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Panier> Panier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Statistiques> Statistiques { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatsQstScience> StatsQstScience { get; set; }
    }
}
