//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Panier
    {
        public int idJoueur { get; set; }
        public int idItem { get; set; }
        public int qtItemPanier { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Joueurs Joueurs { get; set; }
    }
}
