//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Potion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Potion()
        {
            this.Recette = new HashSet<Recette>();
        }
    
        public int idItem { get; set; }
        public string effet { get; set; }
        public int duree { get; set; }
        public string typePotion { get; set; }
    
        public virtual Items Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recette> Recette { get; set; }
    }
}
