//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recette
    {
        public int Potions_idItem { get; set; }
        public int Element_idItem { get; set; }
        public int qtElement { get; set; }
        public Nullable<int> Element_idItem2 { get; set; }
    
        public virtual elements elements { get; set; }
        public virtual Potion Potion { get; set; }
    }
}
