//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chevaleresk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reponses
    {
        public int idReponse { get; set; }
        public string laReponse { get; set; }
        public string estBonne { get; set; }
        public int idQuestion { get; set; }
    
        public virtual Questions Questions { get; set; }
    }
}
